#!/bin/bash

# Quick script to enable public access for Strapi content types
# This needs to be done in the Strapi Admin Panel manually

echo "======================================"
echo "STRAPI PERMISSIONS FIX INSTRUCTIONS"
echo "======================================"
echo ""
echo "The homepage and other content are not showing because the Strapi"
echo "content types don't have public read permissions."
echo ""
echo "To fix this, please follow these steps:"
echo ""
echo "1. Go to your Strapi Admin Panel:"
echo "   https://best-desire-8443ae2768.strapiapp.com/admin"
echo ""
echo "2. Navigate to: Settings -> Users & Permissions Plugin -> Roles"
echo ""
echo "3. Click on 'Public' role"
echo ""
echo "4. For each of these content types, check the 'find' and 'findOne' boxes:"
echo "   - About-us: ✓ find"
echo "   - Cause: ✓ find, ✓ findOne"
echo "   - Event: ✓ find, ✓ findOne"
echo "   - Gallery: ✓ find, ✓ findOne"
echo "   - Home-page: ✓ find"
echo "   - Link: ✓ find, ✓ findOne"
echo "   - Service: ✓ find, ✓ findOne"
echo "   - Stat: ✓ find, ✓ findOne"
echo ""
echo "5. Click 'Save' at the top right"
echo ""
echo "After doing this, your website will immediately start showing"
echo "the content from the CMS instead of the hardcoded fallback content."
echo ""
echo "======================================"
echo ""
echo "Testing the APIs after fixing permissions:"
echo ""
echo "Homepage API:"
curl -s "https://best-desire-8443ae2768.strapiapp.com/api/home-page?populate=*" | jq '.data.heroTitle' 2>/dev/null || echo "❌ Still forbidden - please set permissions"
echo ""
echo "Events API:"
curl -s "https://best-desire-8443ae2768.strapiapp.com/api/events" | jq '.data | length' 2>/dev/null || echo "❌ Still forbidden - please set permissions"
echo ""